"""
Statická DB zemí - identická na všech stanicích.

Pořadí (index) odpovídá bitové pozici ve visited_mask na čipu!
NIKDY neměnit pořadí ani indexy mezi sezónami akce - dříve naprogramované
čipy by se zlomily.

Seznam podle reálného plánu akce:
  0  USA Hawaii         - podlejzání tyčí
  1  Francie            - skládačka
  2  Japonsko           - hůlky a stezka
  3  Egypt              - pyramida (šifry)
  4  Itálie             - pojídání špaget
  5  Dánsko             - postaví si Lego
  6  Austrálie          - skákání v pytli
  7  Česká republika    - bude upřesněno
  8  Velká Británie     - Harry Potter
  9  Indie              - poznávání vůní
 10  Antarktida         - lovení rybiček
"""
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Country:
    index: int                    # 0..10, odpovídá bitu na čipu
    code: str                     # 2-3 znaková zkratka, např. 'US_HI'
    name_cz: str                  # 'USA Hawaii'
    locative_cz: str              # 'na Havaji', 've Francii' - s předložkou
    activity_cz: str              # popis aktivity (pro org. dokumentaci)
    facts: List[str] = field(default_factory=list)


# Pořadí MUSÍ odpovídat indexům!
COUNTRIES: List[Country] = [
    Country(
        index=0,
        code="US_HI",
        name_cz="USA Hawaii",
        locative_cz="na Havaji",
        activity_cz="Podlejzání tyčí (limbo)",
        facts=[
            "Hawaii je tvořeno 137 ostrovy.",
            "Na Havaji rostou ovocné stromy, ze kterých padají kokosy.",
            "Havajci tradičně zdobí krk věnci z květin zvanými lei.",
            "Surfování bylo na Havaji vynalezeno před stovkami let.",
            "Sopka Kīlauea na Havaji je jednou z nejaktivnějších na světě.",
            "V havajské abecedě je jen 13 písmen.",
            "Hawaii je 50. stát USA - připojen byl v roce 1959.",
            "Havajská tradiční hudba zní s ukulele.",
            "Na Havaji žije vzácný tuleň jen tady - tuleň havajský.",
            "Pláž Waikiki je nejslavnější pláž na Havaji.",
            "Havajská pizza s ananasem byla vlastně vynalezena v Kanadě.",
            "Hawaii má dva oficiální jazyky - angličtinu a havajštinu.",
            "Tradiční tanec na Havaji se jmenuje hula.",
            "Hawaii leží 4 000 km od pevninských USA.",
            "Na Havaji můžeš vidět želvy zelenavé přímo na pláži.",
            "Národním květem Havaje je ibišek.",
            "Místní pozdrav 'Aloha' znamená i ahoj i nashledanou.",
            "Hawaii byla kdysi království se svým králem.",
            "Mauna Kea, hora na Havaji, je od základu vyšší než Everest.",
            "Na Havaji prší v některých místech přes 300 dní v roce.",
            "Havajská kuchyně používá hodně poké - syrové ryby s rýží.",
        ],
    ),
    Country(
        index=1,
        code="FR",
        name_cz="Francie",
        locative_cz="ve Francii",
        activity_cz="Skládačka",
        facts=[
            "Eiffelova věž v Paříži má 1 665 schodů na vrchol.",
            "Francouzi snědí ročně přes 30 000 tun sýrů.",
            "Ve Francii se podává na talíři přes 400 různých druhů sýrů.",
            "Louvre v Paříži je největší muzeum na světě.",
            "Francouzi pojmenovali horkovzdušný balón po bratrech Montgolfierových.",
            "Francouzská bageta je dlouhá obvykle 65 cm.",
            "Tour de France je nejslavnější cyklistický závod na světě.",
            "Disneyland Paříž je největší zábavní park v Evropě.",
            "Mont Blanc, nejvyšší hora Evropy, leží z části ve Francii.",
            "Francouzi vynalezli filmovou kameru.",
            "Slavná Mona Lisa visí v Louvru a každý rok ji vidí 10 milionů lidí.",
            "Versailleský zámek má 700 místností.",
            "Francouzi vynalezli šampaňské.",
            "Ve Francii jsou hrady Loiry - přes 300 zámků v jednom údolí.",
            "Eiffelova věž měla být postavena jen dočasně.",
            "Pařížské metro má 16 linek.",
            "Francouzský prezident bydlí v Élysejském paláci.",
            "Marseille je nejstarší město Francie - založeno před 2 600 lety.",
            "Francouzský polibek na obě tváře je tradiční pozdrav.",
            "Vlajka Francie má tři pruhy - modrý, bílý a červený.",
            "Notre-Dame v Paříži byla stavěna 182 let.",
        ],
    ),
    Country(
        index=2,
        code="JP",
        name_cz="Japonsko",
        locative_cz="v Japonsku",
        activity_cz="Hůlky a stezka",
        facts=[
            "V Japonsku je víc než 5 milionů automatů - koupíš si v nich i horký čaj.",
            "Japonci mají přes 200 různých druhů sushi.",
            "Hora Fudži je nejvyšší japonská hora a je to vlastně sopka.",
            "V Japonsku se kloní místo podávání ruky.",
            "Tokyjské metro má speciální pomocníky, kteří mačkají lidi do vagonů.",
            "Japonsko má víc než 6 800 ostrovů.",
            "Japonské vlaky šinkansen jezdí 320 km/h.",
            "V Japonsku vznikla pokémonová série.",
            "Třešňové květy 'sakura' jsou národním symbolem.",
            "Japonský bonsai se pěstuje stovky let.",
            "Origami - umění skládání papíru - pochází z Japonska.",
            "Pizza v Japonsku má někdy chobotnice a kukuřici.",
            "V Japonsku jsou na ulici občerstvovací automaty s polévkou.",
            "Tradiční japonský dům má v podlaze podlahu z rohoží zvaných tatami.",
            "Japonské znaky pochází z Číny - používá se přes 2 000.",
            "Karaoke bylo vynalezeno v Japonsku v 70. letech.",
            "Japonské toalety mají vyhřívanou desku a hudbu.",
            "V Tokiu žije přes 13 milionů lidí.",
            "Japonsko zažívá ročně přes 1 500 zemětřesení.",
            "Tradiční japonský oděv se jmenuje kimono.",
            "Manga jsou japonské komiksy a mají miliardy fanoušků.",
        ],
    ),
    Country(
        index=3,
        code="EG",
        name_cz="Egypt",
        locative_cz="v Egyptě",
        activity_cz="Pyramida (šifry)",
        facts=[
            "Velká pyramida v Gíze stojí už přes 4 500 let.",
            "Egyptská kočka byla považována za posvátné zvíře.",
            "Řeka Nil je nejdelší řeka světa - měří přes 6 600 km.",
            "Staří Egypťané vynalezli papír z papyru.",
            "V Egyptě téměř nikdy neprší, protože je tam poušť.",
            "Pyramidy stavěli dělníci, ne otroci - dostávali pivo a chleba.",
            "Egyptské hieroglyfy obsahují přes 700 různých symbolů.",
            "Faraon Tutanchamon zemřel, když mu bylo 19 let.",
            "Egypťané věřili, že srdce je sídlem rozumu, ne mozek.",
            "Egypťané vynalezli kalendář s 365 dny.",
            "Cheopsova pyramida byla 3 800 let nejvyšší stavbou světa.",
            "V Egyptě se piloti učili balzamování těl.",
            "Sfinga v Gíze má tělo lva a hlavu člověka.",
            "Egypťané hráli stolní hry už před 5 000 lety.",
            "Mumie v Egyptě se balzamovaly i pro zvířata - kočky, krokodýly.",
            "Cleopatra mluvila 9 jazyky.",
            "V Egyptě se vyrábí asi 200 druhů chleba.",
            "Suezský průplav v Egyptě spojuje Evropu a Asii.",
            "Egyptský bůh Slunce se jmenoval Ra.",
            "Egyptská kuchyně používá hodně koření kmín a koriandr.",
            "Egypťané hráli s míčem už před 4 000 lety.",
        ],
    ),
    Country(
        index=4,
        code="IT",
        name_cz="Itálie",
        locative_cz="v Itálii",
        activity_cz="Pojídání špaget",
        facts=[
            "Pizza pochází z italského města Neapol.",
            "V Itálii je víc než 1 500 jezer.",
            "Šikmá věž v Pise se naklání už od svého postavení v roce 1173.",
            "V italských Benátkách se místo aut jezdí lodičkami zvanými gondoly.",
            "Italové vynalezli zmrzlinu zvanou gelato.",
            "V Itálii je víc než 100 druhů sýrů.",
            "Italové snědí ročně přes 23 kg těstovin na osobu.",
            "Římské Koloseum se vejde 50 000 diváků.",
            "Itálie má tvar boty.",
            "Vatikán uvnitř Říma je nejmenší stát světa.",
            "V Itálii je víc než 3 000 muzeí.",
            "Italská opera vznikla v 16. století.",
            "Špagety se jí vidličkou, ne lžící.",
            "V Itálii je víc než 50 míst zapsaných v UNESCO.",
            "Ferrari, Lamborghini a Maserati jsou italské značky aut.",
            "Vesuv u Neapole je jednou z aktivních sopek v Evropě.",
            "Pizza Margherita je pojmenována po italské královně.",
            "Italský pozdrav 'Ciao' se používá i jako 'ahoj' i 'nashledanou'.",
            "Šikmá věž v Pise se naklání už o 4 metry.",
            "Italský parmezán musí být zrát alespoň 12 měsíců.",
            "Itálie je domovem 21 % všech antických památek světa.",
        ],
    ),
    Country(
        index=5,
        code="DK",
        name_cz="Dánsko",
        locative_cz="v Dánsku",
        activity_cz="Stavba z Lega",
        facts=[
            "LEGO bylo vynalezeno v Dánsku v roce 1932.",
            "Slovo LEGO pochází z dánských slov 'leg godt' - 'hraj si dobře'.",
            "Dánsko má víc než 400 ostrovů.",
            "Vlajka Dánska je nejstarší státní vlajka na světě.",
            "V Dánsku žije 5,9 milionu lidí.",
            "Dánská hlavní město je Kodaň.",
            "V dánském Legolandu je víc než 65 milionů kostiček Lega.",
            "Dánsko má víc kol než aut.",
            "Slavná pohádkář Hans Christian Andersen byl Dán.",
            "Malá mořská víla z pohádky má sochu v Kodani.",
            "Dánsko je často hodnoceno jako nejšťastnější země na světě.",
            "V Dánsku je 7 414 km pobřeží.",
            "Dánské svatomartinské housky jedí po celém světě.",
            "Dánsko vyhrálo fotbalové ME v roce 1992.",
            "Dánové vynalezli reproduktor Bang & Olufsen.",
            "Dánové milují svíčky - používají jich nejvíc na světě.",
            "V Dánsku je víc Lega než lidí.",
            "Dánská královská rodina je jednou z nejstarších v Evropě.",
            "Vikingové pocházeli z dánské oblasti.",
            "Dánsko nemá hory - nejvyšší bod má jen 171 metrů.",
            "Z dánských dvorů se stavělo Lego LEGO House.",
        ],
    ),
    Country(
        index=6,
        code="AU",
        name_cz="Austrálie",
        locative_cz="v Austrálii",
        activity_cz="Skákání v pytli",
        facts=[
            "V Austrálii žije víc klokanů než lidí.",
            "Velký bariérový útes je tak velký, že je vidět z vesmíru.",
            "V Austrálii mají Vánoce v létě a chodí o nich na pláž.",
            "Koaly nepijí vodu - všechnu tekutinu získávají z eukalyptových listů.",
            "Austrálie je jediný kontinent, kde se nachází jeden stát.",
            "V Austrálii je 60 % všech ovcí na světě.",
            "Klokan dokáže skočit 9 metrů daleko.",
            "Sydney Opera House má více než milion střešních dlaždic.",
            "V Austrálii žije 10 z 25 nejjedovatějších hadů světa.",
            "Velký bariérový útes je delší než 2 300 km.",
            "Australané říkají 'mate' místo 'kamaráde'.",
            "V Austrálii žije ptakopysk - savec, který klade vejce.",
            "Austrálie má 10 685 pláží.",
            "V Austrálii je město pojmenované Mount Disappointment - 'Hora zklamání'.",
            "Australské pobřeží je dlouhé 25 000 km.",
            "V Austrálii žije přes 1 500 druhů pavouků.",
            "Národní mistrovství v honbě za žábami se koná v Austrálii.",
            "Wallabies žijí jen v Austrálii - jsou menší než klokani.",
            "Austrálie má růžová jezera s velmi slanou vodou.",
            "Tasmánský čert je malý dravec žijící jen v Austrálii.",
            "V Austrálii je tak velké slunce, že lidé musí nosit klobouky stále.",
        ],
    ),
    Country(
        index=7,
        code="CZ",
        name_cz="Česká republika",
        locative_cz="v Česku",
        activity_cz="Bude upřesněno",
        facts=[
            "Česko má víc než 2 000 hradů a zámků - nejvíc na světě podle plochy.",
            "Pražský hrad je největší hradní komplex na světě.",
            "Češi vypijí nejvíc piva na osobu na světě.",
            "Karlův most v Praze stojí už od roku 1357.",
            "Čeština má 42 písmen v abecedě.",
            "Hokejisté z ČR vyhráli olympiádu v Naganu v roce 1998.",
            "České slovo 'robot' používá celý svět - vymyslel ho Karel Čapek.",
            "V ČR žije asi 10,5 milionu lidí.",
            "Nejvyšší hora Česka je Sněžka - 1 603 metrů.",
            "Pražská zoo je jedna z nejlepších na světě.",
            "Knedlíky jsou české jídlo, ale variantu mají i jinde.",
            "Český Krumlov je celý zapsán v UNESCO.",
            "České sklo a křišťál jsou slavné po celém světě.",
            "Vynálezem v ČR jsou kontaktní čočky.",
            "Praha má historicky nejstarší univerzitu ve střední Evropě - založena 1348.",
            "V Česku se vyrábí Škoda auta od roku 1895.",
            "Letohrádek Hvězda v Praze má půdorys šesticípé hvězdy.",
            "České loutkářství je zapsáno v UNESCO.",
            "Marionetové divadlo v ČR má tradici 600 let.",
            "Bramborový salát s řízkem je tradiční české vánoční jídlo.",
            "V Plzni se vaří pivo Pilsner od roku 1842.",
        ],
    ),
    Country(
        index=8,
        code="GB",
        name_cz="Velká Británie",
        locative_cz="ve Velké Británii",
        activity_cz="Harry Potter",
        facts=[
            "V Británii žila spisovatelka J. K. Rowling, která napsala Harryho Pottera.",
            "Anglickou královskou rodinu vede král Karel III.",
            "Big Ben je vlastně název zvonu, ne věže.",
            "V Londýně je metro nejstarší na světě - z roku 1863.",
            "Britové pijí 165 milionů šálků čaje denně.",
            "Londýnské metro se říká 'The Tube'.",
            "Britská královna měla narozeniny oficiálně dvakrát ročně.",
            "Hogwarts ve filmech točili na hradě Alnwick v Anglii.",
            "Britské libry jsou rozdělené na 100 pencí.",
            "V Londýně jsou typické černé taxíky 'cab'.",
            "Stonehenge je starý přes 5 000 let.",
            "Britové jezdí autem na levé straně silnice.",
            "Buckingham Palace má 775 místností.",
            "V Británii vyhrál Lennon a McCartney s Beatles celý svět.",
            "Anglická královna měla flotilu labutí - patří jí všechny labutě v Anglii.",
            "Studie filmů o Harrym Potterovi jsou Warner Bros. Studio Tour.",
            "V Londýně mají červené dvoupatrové autobusy.",
            "Britský humor je slavný po celém světě.",
            "V Anglii hrají rugby, fotbal i kriket - všechno vynalezli oni.",
            "Britská policie nenosí běžně zbraně.",
            "Harry Potter byl přeložen do více než 80 jazyků.",
        ],
    ),
    Country(
        index=9,
        code="IN",
        name_cz="Indie",
        locative_cz="v Indii",
        activity_cz="Poznávání vůní",
        facts=[
            "V Indii žije přes 1,4 miliardy lidí.",
            "Tádž Mahal byl postaven z lásky před více než 350 lety.",
            "V Indii se mluví více než 700 různými jazyky.",
            "Šachy byly vynalezeny v Indii.",
            "Indická kuchyně používá přes 40 druhů koření.",
            "Indie má víc poštovních úřadů než kterákoli jiná země.",
            "Krávy jsou v Indii považovány za posvátná zvířata.",
            "Bollywood je největší filmový průmysl na světě.",
            "Indie má jeden z nejmokřejších míst na světě - Mawsynram.",
            "Tygr je národní zvíře Indie.",
            "Číslo nula bylo vynalezeno v Indii.",
            "V Indii se každoročně slaví Festival barev - Holi.",
            "Indický čaj 'chai' obsahuje koření a mléko.",
            "Joga pochází z Indie a je stará 5 000 let.",
            "V Indii je víc než 300 000 mešit.",
            "Indie má nejstarší hudební nástroje na světě.",
            "V Indii žije nejvíc vegetariánů na světě.",
            "Pepř, kardamom a hřebíček byly objeveny v Indii.",
            "Indický Diwali je festival světel.",
            "Sárí je tradiční ženský oděv v Indii.",
            "V Indii je víc než 50 jazyků s vlastním písmem.",
        ],
    ),
    Country(
        index=10,
        code="AQ",
        name_cz="Antarktida",
        locative_cz="na Antarktidě",
        activity_cz="Lovení rybiček",
        facts=[
            "Antarktida je nejchladnější místo na Zemi - až -89 °C.",
            "Na Antarktidě žije 18 druhů tučňáků.",
            "Antarktida je obklopená oceánem - Jižním ledovým.",
            "Pod ledem Antarktidy je jezero stará 14 milionů let.",
            "Antarktida má 70 % veškeré sladké vody na světě.",
            "V Antarktidě nikdy nikdo nezemřel - žádné autonehody, žádné kriminálníky.",
            "V zimě je na Antarktidě tma 6 měsíců.",
            "V Antarktidě nesmí žít žádné jiné savce kromě vědců a tučňáků.",
            "Plocha Antarktidy je větší než Evropa.",
            "Pod antarktickým ledem jsou pohoří větší než Alpy.",
            "V Antarktidě je trvalá ledová kupole vysoká až 4 km.",
            "Bankomaty jsou jen dva - v americké stanici McMurdo.",
            "V létě na Antarktidu jezdí přes 5 000 vědců.",
            "Tučňák císařský je největší tučňák - měří až 120 cm.",
            "Antarktická tlustá ryba má v krvi 'nemrznoucí' bílkoviny.",
            "Antarktidu objevili lidé až v roce 1820.",
            "Nikdo nevlastní Antarktidu - patří všem zemím podle smlouvy.",
            "V Antarktidě jsou jezera, která se nikdy nezamrznou.",
            "Krevety krill jsou hlavní potravou velryb v Antarktidě.",
            "V Antarktidě nesmíš nic vzít - ani kamínek na památku.",
            "Antarktida je největší poušť na světě - téměř neprší.",
        ],
    ),
]


def get_country_by_index(idx: int) -> Optional[Country]:
    if 0 <= idx < len(COUNTRIES):
        return COUNTRIES[idx]
    return None


def get_country_by_code(code: str) -> Optional[Country]:
    for c in COUNTRIES:
        if c.code == code:
            return c
    return None
